name: build
on:
  push

jobs:
  coverage:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install yarn
        run: npm install yarn
      - name: install packages
        run: yarn
      - name: compile
        run: yarn compile
